import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  /**
   * TRPC nos deja crear funciones que se ejecutan en el servidor, que en este
    caso es Vercel. Nos permite obtener datos de la BD, por ejemplo. No nos
    conectamos directamente a la BD. Desplegamos esta forma de conectarnos a la
    BD, facilitando incluso la forma en la que nos conectamos para obtener esta
    información, a pesar de que se encuentre en otro servidor. 
  */
  const { data } = api.example.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="text-white">
          {!user.isSignedIn && <SignInButton />}
          {user.isSignedIn && <SignOutButton />}
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
