import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import { Container, Card, Row, Text } from "@nextui-org/react"
import Header from "../components/Header"

import fs from "fs/promises"
import Link from "next/link"

export default function Home({ latestComics }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <h2>Latest Comics</h2>
        {latestComics.map((comic) => (
          <Link href={`/comic/${comic.id}`} key={comic.id}>
            <a>
              {/* No utilizamos <Image /> porque no conocemos width ni height 
              de las imágenes y el componente lo pide. */}
              <img src={comic.img} alt={comic.alt} />
              {/* <Image layout="fill" src={comic.img} alt={comic.alt} /> */}
            </a>
          </Link>
        ))}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const files = await fs.readdir("./comics")
  const latestComicsFiles = files.slice(-8, files.length)

  // Arreglo de promesas con el contenido de cada archivo.
  const promisesReadFiles = latestComicsFiles.map(async (fileName) => {
    const content = await fs.readFile(`./comics/${fileName}`, "utf-8")

    // No necesitamos hacer un objeto con el spred porque solo regresaremos ese
    // objeto sin otras propiedades.
    /* return { ...JSON.parse(content) } */

    return JSON.parse(content)
  })

  // Resolvemos las promesas que se crearon cuando se leyeron los archivos.
  const latestComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      latestComics,
    },
  }
}
