import Head from "next/head"
import Link from "next/link"
import Image from "next/image"

import { Header } from "components/Header"
import { Footer } from "components/Footer"

import fs from "node:fs/promises"
import { Layout } from "components/Layout"
import { useI18n } from "context/i18n"

export default function Home({ latestComics }) {
  const { t } = useI18n()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Layout>
        <h2 className="mb-10 text-center text-3xl font-bold">
          {t("LATEST_COMICS")}
        </h2>
        <section className="m-auto grid max-w-lg grid-cols-1 gap-2 sm:grid-cols-2 md:grid-cols-3">
          {latestComics.map((comic) => (
            <Link href={`/comic/${comic.id}`} key={comic.id}>
              <a className="m-auto mb-4 pb-4">
                <h3 className="pb-2 text-center text-sm font-bold">
                  {comic.title}
                </h3>
                {/* No utilizamos <Image /> porque no conocemos width ni height
                de las imágenes y el componente lo pide. */}
                <Image
                  width={300}
                  height={300}
                  // width={comic.width}
                  // height={comic.height}
                  layout="intrinsic"
                  objectFit="contain"
                  src={comic.img}
                  alt={comic.alt}
                />
                {/* <Image layout="fill" src={comic.img} alt={comic.alt} /> */}
              </a>
            </Link>
          ))}
        </section>
      </Layout>
    </>
  )
}

export async function getStaticProps() {
  const files = await fs.readdir("./comics")
  const latestComicsFiles = files.slice(-8, files.length)

  // Arreglo de promesas con el contenido de cada archivo.
  const promisesReadFiles = latestComicsFiles.map(async (fileName) => {
    const content = await fs.readFile(`./comics/${fileName}`, "utf-8")

    // No necesitamos hacer un objeto con el spred porque solo regresaremos ese
    // objeto sin otras propiedades.
    /* return { ...JSON.parse(content) } */

    return JSON.parse(content)
  })

  // Resolvemos las promesas que se crearon cuando se leyeron los archivos.
  const latestComics = await Promise.all(promisesReadFiles)

  return {
    props: {
      latestComics,
    },
  }
}
